<template>
  <div>
    <lo-list>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
      <lo-list-item-single-line
        title="Test"
        subTitle="TestSubtitle"></lo-list-item-single-line>
    </lo-list>
  </div>
</template>

<script>
  export default {};
</script>
